apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fddb-exporter.fullname" . }}
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fddb-exporter.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fddb-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fddb-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "fddb-exporter.fullname" . }}-config
          env:
            - name: FDDB-EXPORTER_FDDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ if not .Values.fddb.auth.secretRef.name }}{{ include "fddb-exporter.fullname" . }}-fddb{{ else }}{{ .Values.fddb.auth.secretRef.name }}{{ end }}
                  key: FDDB-EXPORTER_FDDB_USERNAME
            - name: FDDB-EXPORTER_FDDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if not .Values.fddb.auth.secretRef.name }}{{ include "fddb-exporter.fullname" . }}-fddb{{ else }}{{ .Values.fddb.auth.secretRef.name }}{{ end }}
                  key: FDDB-EXPORTER_FDDB_PASSWORD
            {{- if .Values.mongodb.enabled }}
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if not .Values.mongodb.secretRef.name }}{{ include "fddb-exporter.fullname" . }}-mongodb{{ else }}{{ .Values.mongodb.secretRef.name }}{{ end }}
                  key: SPRING_DATA_MONGODB_PASSWORD
            {{- end }}
            {{- if .Values.influxdb.enabled }}
            - name: FDDB-EXPORTER_INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if not .Values.influxdb.secretRef.name }}{{ include "fddb-exporter.fullname" . }}-influxdb{{ else }}{{ .Values.influxdb.secretRef.name }}{{ end }}
                  key: FDDB-EXPORTER_INFLUXDB_TOKEN
            {{- end }}
          ports:
              - name: http
                containerPort: {{ .Values.service.port }}
                protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}