{{- if and .Values.mongodb.enabled (not .Values.mongodb.secretRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fddb-exporter.fullname" . }}-mongodb
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc }}
---
{{- end }}

{{- if and .Values.influxdb.enabled (not .Values.influxdb.secretRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fddb-exporter.fullname" . }}-influxdb
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  FDDB_EXPORTER_INFLUXDB_TOKEN: {{ .Values.influxdb.token | b64enc }}
---
{{- end }}

{{- if not .Values.fddb.auth.secretRef.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fddb-exporter.fullname" . }}-fddb
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  FDDB-EXPORTER_FDDB_USERNAME: {{ .Values.fddb.auth.username | b64enc }}
  FDDB-EXPORTER_FDDB_PASSWORD: {{ .Values.fddb.auth.password | b64enc }}
{{- end }}