{{- if and .Values.mongodb.enabled (eq .Values.mongodb.enabled "true") (eq .Values.mongodb.secretRef.name "placeholder-mongodb-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fddb-exporter.fullname" . }}-mongodb
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATA_MONGODB_PASSWORD: {{ .Values.mongodb.password | b64enc }}
---
{{- end }}

{{- if and .Values.influxdb.enabled (eq .Values.influxdb.enabled "true") (eq .Values.influxdb.secretRef.name "placeholder-influxdb-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fddb-exporter.fullname" . }}-influxdb
  labels:
    {{- include "fddb-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  FDDB_EXPORTER_INFLUXDB_TOKEN: {{ .Values.influxdb.token | b64enc }}
{{- end }}
