apiVersion: v2
name: playlist-mirror
description: A Helm chart for Playlist Mirror
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: itobey
    email: helm@itobey.dev
home: https://github.com/itobey/playlist-mirror
sources:
  - https://github.com/itobey/playlist-mirror
annotations:
  artifacthub.io/signKey: |
    fingerprint: 72B5513C9AFD0D076A4A74F16568CD480699F07C
    url: https://raw.githubusercontent.com/itobey/charts/master/helm-signing-key.asc
