apiVersion: v2
name: fddb-exporter
description: A Helm chart for FDDB Exporter
version: 2.2.0
appVersion: "2.2.0"
maintainers:
  - name: itobey
    email: helm@itobey.dev
home: https://github.com/itobey/fddb-exporter
sources:
  - https://github.com/itobey/fddb-exporter