apiVersion: v2
name: fddb-exporter
description: A Helm chart for FDDB Exporter
version: 2.4.2
appVersion: "2.4.1"
maintainers:
  - name: itobey
    email: helm@itobey.dev
home: https://github.com/itobey/fddb-exporter
sources:
  - https://github.com/itobey/fddb-exporter
annotations:
  artifacthub.io/signKey: |
    fingerprint: 72B5513C9AFD0D076A4A74F16568CD480699F07C
    url: https://raw.githubusercontent.com/itobey/charts/master/helm-signing-key.asc
